# trajnet-sdd sfm laplacian distance fn. weight 30.0 b 1.00 training cfg for dlow models trained w/ collision loss
# og name: trajnet_sdd_pre3_dlow.yml

# ------------------- General Options -------------------------

description: AgentFormer (DLow)
results_root_dir: results-joint
seed: 1
dataset: trajnet_sdd
data_root_ethucy: datasets/eth_ucy
data_root_nuscenes_pred: datasets/nuscenes_pred
data_root_sdd: datasets/sdd
data_root_trajnet_sdd: datasets/trajnet_sdd

# ------------------- Feature Extractor -------------------------

frame_skip: 1
past_frames: 8
future_frames: 12
min_past_frames: 2
min_future_frames: 2

traj_scale: 10
motion_dim: 2
forecast_dim: 2

# ------------------- Model -------------------------

model_id: dlow
pred_cfg: trajnet_sdd_pre3
pred_epoch: 100
qnet_mlp: [512, 256]
share_eps: true
train_w_mean: true

# ------------------- VAE-------------------------

nz: 32
sample_k: 20

# ------------------- Training Parameters -------------------------

lr: 1.e-4
loss_cfg:
  kld:
    weight: 0.1
    min_clip: 10
  diverse:
    weight: 20
    d_scale: 10
  joint_recon:
    weight: 5.0  
  sample_sfm:
    weight: 30.0
    sfm_params:
      dist_fn: laplacian
      b: 1.0
      use_w: False
      loss_reduce: mean

num_epochs: 50
lr_fix_epochs: 10
lr_scheduler: "step"
decay_step: 5
decay_gamma: 0.5
print_freq: 20
model_save_freq: 5
